"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").strip().lower() in {"1", "true", "yes", "on"}

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be configured when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = []

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_SERVICE_SUGGESTION_MODEL = os.getenv(
    "OPENAI_SERVICE_SUGGESTION_MODEL",
    "gpt-4.1-mini",
)
SITEEXPRESS_ASSISTANT_MODEL = os.getenv("SITEEXPRESS_ASSISTANT_MODEL", "gpt-5.4-mini")
SITEEXPRESS_ASSISTANT_MODE = os.getenv("SITEEXPRESS_ASSISTANT_MODE", "auto").strip().lower()
SITEEXPRESS_ASSISTANT_MAX_MESSAGE_LENGTH = int(
    os.getenv("SITEEXPRESS_ASSISTANT_MAX_MESSAGE_LENGTH", "1200")
)
SITEEXPRESS_ASSISTANT_MAX_HISTORY_MESSAGES = int(
    os.getenv("SITEEXPRESS_ASSISTANT_MAX_HISTORY_MESSAGES", "10")
)
SITEEXPRESS_ASSISTANT_INPUT_USD_PER_MILLION = os.getenv(
    "SITEEXPRESS_ASSISTANT_INPUT_USD_PER_MILLION",
    "0.75",
)
SITEEXPRESS_ASSISTANT_CACHED_INPUT_USD_PER_MILLION = os.getenv(
    "SITEEXPRESS_ASSISTANT_CACHED_INPUT_USD_PER_MILLION",
    "0.075",
)
SITEEXPRESS_ASSISTANT_OUTPUT_USD_PER_MILLION = os.getenv(
    "SITEEXPRESS_ASSISTANT_OUTPUT_USD_PER_MILLION",
    "4.50",
)
SITEEXPRESS_WHATSAPP_NUMBER = os.getenv("SITEEXPRESS_WHATSAPP_NUMBER", "").strip()
SITEEXPRESS_FACEBOOK_URL = os.getenv("SITEEXPRESS_FACEBOOK_URL", "").strip()
SITEEXPRESS_INSTAGRAM_URL = os.getenv("SITEEXPRESS_INSTAGRAM_URL", "").strip()
SITEEXPRESS_LINKEDIN_URL = os.getenv("SITEEXPRESS_LINKEDIN_URL", "").strip()
SITEEXPRESS_GOOGLE_BUSINESS_URL = os.getenv("SITEEXPRESS_GOOGLE_BUSINESS_URL", "").strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'onboarding',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'onboarding.context_processors.public_site_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt'

TIME_ZONE = 'Europe/Lisbon'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('pt', 'Portuguese'),
    ('es', 'Spanish'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
