# Generated by Django 5.2.9 on 2026-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='custom_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
