# Generated by Django 5.2.9 on 2026-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_colorscheme_custom_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorscheme',
            name='user_color_choice',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('black', 'Black'), ('custom', 'Custom')], max_length=10),
        ),
    ]
