# Generated by Django 5.2.9 on 2026-05-05 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_colorscheme_user_color_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business name')),
                ('business_type', models.CharField(max_length=120, verbose_name='Business type')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Region')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('preferred_colors', models.JSONField(blank=True, default=list, verbose_name='Preferred colors')),
                ('target_country', models.CharField(blank=True, max_length=120, verbose_name='Target country')),
                ('target_city', models.CharField(blank=True, max_length=120, verbose_name='Target city')),
                ('target_region', models.CharField(blank=True, max_length=120, verbose_name='Target region')),
                ('target_audience', models.TextField(blank=True, verbose_name='Target audience')),
                ('target_language', models.CharField(default='pt', max_length=20, verbose_name='Target language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Business profile',
                'verbose_name_plural': 'Business profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='pt', max_length=20, verbose_name='Language')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Hero title')),
                ('hero_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Hero subtitle')),
                ('intro_text', models.TextField(blank=True, verbose_name='Intro text')),
                ('services_json', models.JSONField(blank=True, default=list, verbose_name='Services')),
                ('about_text', models.TextField(blank=True, verbose_name='About text')),
                ('cta_text', models.CharField(blank=True, max_length=255, verbose_name='Call to action text')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generated content',
                'verbose_name_plural': 'Generated content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StarterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_preview', models.BooleanField(default=True, verbose_name='Is preview')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Starter page',
                'verbose_name_plural': 'Starter pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_interest', models.CharField(choices=[('starter_monthly', 'Starter monthly'), ('standard_full_website', 'Standard full website'), ('premium_bilingual', 'Premium bilingual')], default='starter_monthly', max_length=32, verbose_name='Plan interest')),
                ('status', models.CharField(choices=[('onboarding_started', 'Onboarding started'), ('content_generated', 'Content generated'), ('starter_preview_ready', 'Starter preview ready'), ('wordpress_draft_ready', 'WordPress draft ready'), ('upgraded', 'Upgraded'), ('published', 'Published')], default='onboarding_started', max_length=32, verbose_name='Status')),
                ('starter_page_enabled', models.BooleanField(default=True, verbose_name='Starter page enabled')),
                ('wordpress_upgrade_available', models.BooleanField(default=True, verbose_name='WordPress upgrade available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='onboarding.businessprofile', verbose_name='Business profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_projects', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Website project',
                'verbose_name_plural': 'Website projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordPressSiteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft_pending', 'Draft pending'), ('content_ready', 'Content ready'), ('waiting_for_upgrade', 'Waiting for upgrade'), ('ready_to_publish', 'Ready to publish'), ('published', 'Published')], default='waiting_for_upgrade', max_length=32, verbose_name='Status')),
                ('wp_site_url', models.URLField(blank=True, verbose_name='WordPress site URL')),
                ('wp_admin_url', models.URLField(blank=True, verbose_name='WordPress admin URL')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_draft', to='onboarding.websiteproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'WordPress site draft',
                'verbose_name_plural': 'WordPress site drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='ColorScheme',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='starterpage',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starter_page', to='onboarding.websiteproject', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='onboarding.websiteproject', verbose_name='Project'),
        ),
    ]
