# Generated by Django 5.2.9 on 2026-06-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_businessprofile_generatedcontent_starterpage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteproject",
            name="alternative_domain_1",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alternative domain 1"),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="alternative_domain_2",
            field=models.CharField(blank=True, max_length=255, verbose_name="Alternative domain 2"),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="domain_choice",
            field=models.CharField(
                choices=[
                    ("already_have_domain", "Already have domain"),
                    ("need_help", "Need help"),
                    ("preview_only", "Preview only"),
                ],
                default="preview_only",
                max_length=32,
                verbose_name="Domain choice",
            ),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="existing_domain",
            field=models.CharField(blank=True, max_length=255, verbose_name="Existing domain"),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="preferred_domain",
            field=models.CharField(blank=True, max_length=255, verbose_name="Preferred domain"),
        ),
        migrations.CreateModel(
            name="DomainRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_domain", models.CharField(blank=True, max_length=255, verbose_name="Requested domain")),
                ("alternative_domain_1", models.CharField(blank=True, max_length=255, verbose_name="Alternative domain 1")),
                ("alternative_domain_2", models.CharField(blank=True, max_length=255, verbose_name="Alternative domain 2")),
                ("preview_subdomain", models.CharField(blank=True, max_length=255, verbose_name="Preview subdomain")),
                (
                    "domain_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not requested"),
                            ("requested", "Requested"),
                            ("checking", "Checking"),
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("waiting_customer", "Waiting customer"),
                            ("registered_manual", "Registered manually"),
                            ("dns_pending", "DNS pending"),
                            ("dns_connected", "DNS connected"),
                            ("live", "Live"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_requested",
                        max_length=32,
                        verbose_name="Domain status",
                    ),
                ),
                ("registrar", models.CharField(blank=True, max_length=255, verbose_name="Registrar")),
                ("registrant_name", models.CharField(blank=True, max_length=255, verbose_name="Registrant name")),
                ("registrant_vat_or_nif", models.CharField(blank=True, max_length=80, verbose_name="Registrant VAT or NIF")),
                ("registrant_address", models.TextField(blank=True, verbose_name="Registrant address")),
                ("registrant_email", models.EmailField(blank=True, max_length=254, verbose_name="Registrant email")),
                ("registrant_phone", models.CharField(blank=True, max_length=50, verbose_name="Registrant phone")),
                ("public_note", models.TextField(blank=True, verbose_name="Public note")),
                ("admin_note", models.TextField(blank=True, verbose_name="Admin note")),
                ("registered_at", models.DateTimeField(blank=True, null=True, verbose_name="Registered at")),
                ("dns_connected_at", models.DateTimeField(blank=True, null=True, verbose_name="DNS connected at")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_requests",
                        to="onboarding.businessprofile",
                        verbose_name="Business profile",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_request",
                        to="onboarding.websiteproject",
                        verbose_name="Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain request",
                "verbose_name_plural": "Domain requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
