# Generated by Django 5.2.9 on 2026-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_websiteproject_alternative_domain_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='billing_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('one_time', 'One time')], default='monthly', max_length=16, verbose_name='Billing type'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='currency',
            field=models.CharField(default='EUR', max_length=8, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price snapshot'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='product_status',
            field=models.CharField(choices=[('selected', 'Selected'), ('generating', 'Generating'), ('preview_ready', 'Preview ready'), ('customer_reviewing', 'Customer reviewing'), ('upgrade_available', 'Upgrade available'), ('upgrade_requested', 'Upgrade requested'), ('payment_pending', 'Payment pending'), ('payment_confirmed', 'Payment confirmed'), ('publishing_pending', 'Publishing pending'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='selected', max_length=32, verbose_name='Product status'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='product_type',
            field=models.CharField(choices=[('starter_page_monthly', 'Pagina Express'), ('full_website_onetime', 'Website Completo')], default='starter_page_monthly', max_length=32, verbose_name='Product type'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial ends at'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='trial_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Trial months'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial started at'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='upgrade_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('available', 'Available'), ('requested', 'Requested'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='available', max_length=32, verbose_name='Upgrade status'),
        ),
    ]
