# Generated by Django 5.2.9 on 2026-06-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_websiteproject_billing_type_websiteproject_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp phone')),
                ('partner_code', models.CharField(max_length=64, unique=True, verbose_name='Partner code')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=16, verbose_name='Status')),
                ('default_trial_months', models.PositiveIntegerField(default=1, verbose_name='Default trial months')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=20.0, max_digits=8, verbose_name='Commission amount')),
                ('commission_currency', models.CharField(default='EUR', max_length=8, verbose_name='Commission currency')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='is_partner_trial',
            field=models.BooleanField(default=False, verbose_name='Is partner trial'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='partner_code_snapshot',
            field=models.CharField(blank=True, max_length=64, verbose_name='Partner code snapshot'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='trial_source',
            field=models.CharField(choices=[('none', 'None'), ('partner', 'Partner'), ('admin', 'Admin')], default='none', max_length=16, verbose_name='Trial source'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='onboarding.partner', verbose_name='Partner'),
        ),
        migrations.CreateModel(
            name='PartnerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Customer phone')),
                ('product_type_snapshot', models.CharField(blank=True, max_length=32, verbose_name='Product type snapshot')),
                ('trial_months', models.PositiveIntegerField(default=0, verbose_name='Trial months')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial started at')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial ends at')),
                ('referral_status', models.CharField(choices=[('lead_created', 'Lead created'), ('starter_trial_active', 'Starter trial active'), ('trial_ending_soon', 'Trial ending soon'), ('trial_expired', 'Trial expired'), ('starter_paid', 'Starter paid'), ('upgrade_requested', 'Upgrade requested'), ('full_website_paid', 'Full website paid'), ('cancelled', 'Cancelled')], default='lead_created', max_length=32, verbose_name='Referral status')),
                ('commission_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('available', 'Available'), ('requested', 'Requested'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='not_applicable', max_length=32, verbose_name='Commission status')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Commission amount')),
                ('commission_available_at', models.DateTimeField(blank=True, null=True, verbose_name='Commission available at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_referrals', to='onboarding.businessprofile', verbose_name='Business profile')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='onboarding.partner', verbose_name='Partner')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_referral', to='onboarding.websiteproject', verbose_name='Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_referrals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Partner referral',
                'verbose_name_plural': 'Partner referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
