# Generated by Django 5.2.9 on 2026-07-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0007_partner_websiteproject_is_partner_trial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("page_path", models.CharField(blank=True, max_length=500, verbose_name="Page path")),
                ("page_title", models.CharField(blank=True, max_length=255, verbose_name="Page title")),
                ("model", models.CharField(blank=True, max_length=100, verbose_name="Model")),
                ("mode", models.CharField(choices=[("demo", "Demo"), ("openai", "OpenAI")], default="demo", max_length=16, verbose_name="Mode")),
                ("turn_count", models.PositiveIntegerField(default=0, verbose_name="Turns")),
                ("input_tokens", models.PositiveBigIntegerField(default=0, verbose_name="Input tokens")),
                ("cached_input_tokens", models.PositiveBigIntegerField(default=0, verbose_name="Cached input tokens")),
                ("output_tokens", models.PositiveBigIntegerField(default=0, verbose_name="Output tokens")),
                ("last_message_at", models.DateTimeField(blank=True, null=True, verbose_name="Last message at")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assistant_conversations", to=settings.AUTH_USER_MODEL, verbose_name="User")),
            ],
            options={
                "verbose_name": "Assistant conversation",
                "verbose_name_plural": "Assistant conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], max_length=16, verbose_name="Role")),
                ("content", models.TextField(verbose_name="Content")),
                ("response_id", models.CharField(blank=True, max_length=255, verbose_name="Response ID")),
                ("model", models.CharField(blank=True, max_length=100, verbose_name="Model")),
                ("mode", models.CharField(choices=[("demo", "Demo"), ("openai", "OpenAI")], default="demo", max_length=16, verbose_name="Mode")),
                ("input_tokens", models.PositiveBigIntegerField(default=0, verbose_name="Input tokens")),
                ("cached_input_tokens", models.PositiveBigIntegerField(default=0, verbose_name="Cached input tokens")),
                ("output_tokens", models.PositiveBigIntegerField(default=0, verbose_name="Output tokens")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="onboarding.assistantconversation", verbose_name="Conversation")),
            ],
            options={
                "verbose_name": "Assistant message",
                "verbose_name_plural": "Assistant messages",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
