"""Content definitions for SiteExpress public product pages.

The first public version is intentionally code-backed. Keeping the content in one
catalog gives us one place to review prices, CTAs and claims before a CMS is added.
"""


PUBLIC_PAGES = {
    "wordpress": {
        "meta_title": "Website WordPress para pequenos negócios | SiteExpress.pt",
        "meta_description": "Website WordPress profissional para pequenos negócios em Portugal, com páginas essenciais, contactos, serviços e estrutura SEO básica.",
        "eyebrow": "Website profissional",
        "title": "Um website WordPress claro,",
        "title_emphasis": "preparado para crescer.",
        "intro": "Criamos a estrutura, organizamos os serviços e entregamos um website que ajuda clientes a perceber o negócio e entrar em contacto sem complicações.",
        "primary_label": "Começar o meu website",
        "primary_route": "onboarding",
        "secondary_label": "Ver preços",
        "secondary_route": "pricing",
        "highlights": ["WordPress", "Páginas essenciais", "SEO básico", "Contacto e WhatsApp"],
        "sections": [
            {
                "kicker": "A base certa",
                "title": "Não entregamos apenas uma homepage bonita.",
                "body": "O website é organizado para explicar o negócio, mostrar serviços e encaminhar cada visitante para uma ação útil.",
                "points": [
                    "Página inicial com proposta clara",
                    "Páginas de serviços quando forem necessárias",
                    "Sobre, contactos, localização ou área de serviço",
                    "Formulário, telefone, email e WhatsApp",
                ],
            },
            {
                "kicker": "Entrega prática",
                "title": "Primeiro vê. Depois afinamos e publicamos.",
                "body": "Recolhemos a informação principal, preparamos uma pré-visualização e revemos a estrutura antes da publicação. O website pode receber novas páginas, catálogo, loja ou línguas mais tarde.",
                "points": [
                    "Pré-visualização privada antes da publicação",
                    "Estrutura adaptada ao tipo de negócio",
                    "Preparado para Google, Bing e partilha social",
                    "Possibilidade de manutenção e evolução",
                ],
            },
        ],
        "faqs": [
            ("O domínio está incluído?", "Podemos trabalhar com um domínio existente ou ajudar a tratar de um novo domínio. O custo e a titularidade são confirmados antes do registo."),
            ("Posso alterar o website depois?", "Sim. O objetivo é criar uma base que possa receber novas páginas, conteúdos e funcionalidades sem começar novamente."),
            ("Quanto tempo demora?", "Depois de recebermos os conteúdos essenciais, preparamos a primeira versão para revisão. O prazo final depende da quantidade de páginas e das alterações pedidas."),
        ],
        "cta_title": "Vamos transformar a informação do seu negócio numa presença online profissional.",
        "cta_text": "Comece pelo formulário. A pré-visualização ajuda a decidir a estrutura antes da publicação.",
        "cta_label": "Começar agora",
        "cta_route": "onboarding",
    },
    "starter": {
        "meta_title": "Página Express para começar online | SiteExpress.pt",
        "meta_description": "Página Express para pequenos negócios: serviços, contactos, WhatsApp e presença online simples com mensalidade.",
        "eyebrow": "Página Express",
        "title": "Comece com uma página útil,",
        "title_emphasis": "sem construir tudo de uma vez.",
        "intro": "Uma presença online simples para negócios que precisam mostrar o essencial, receber contactos e deixar espaço para evoluir mais tarde.",
        "primary_label": "Criar Página Express",
        "primary_route": "onboarding",
        "secondary_label": "Comparar opções",
        "secondary_route": "pricing",
        "highlights": ["Uma página", "Serviços principais", "WhatsApp e contacto", "€19,95/mês"],
        "sections": [
            {
                "kicker": "Para começar",
                "title": "Tudo o que o cliente precisa de encontrar primeiro.",
                "body": "A Página Express reúne a apresentação do negócio, os serviços mais importantes e as formas de contacto numa única página rápida e clara.",
                "points": [
                    "Nome, descrição e área de atuação",
                    "Serviços ou produtos principais",
                    "Telefone, email, WhatsApp e localização",
                    "Chamada para pedir informação ou orçamento",
                ],
            },
            {
                "kicker": "Sem ficar preso",
                "title": "Quando o negócio crescer, a presença online acompanha.",
                "body": "Pode pedir um website WordPress completo quando precisar de páginas de serviço, portfólio, catálogo, loja, línguas ou ferramentas adicionais.",
                "points": [
                    "Pré-visualização antes de avançar",
                    "Possibilidade de ligar domínio próprio",
                    "Upgrade para website completo",
                    "Apoio disponível quando necessário",
                ],
            },
        ],
        "faqs": [
            ("É um website completo?", "É uma página única de apresentação. Para várias páginas, conteúdos detalhados ou funcionalidades avançadas, o Website WordPress é a opção adequada."),
            ("Posso usar o meu domínio?", "Sim. Podemos analisar um domínio existente ou ajudar com um novo domínio."),
            ("Posso cancelar?", "As condições de cancelamento e o período já pago são apresentados antes da ativação do serviço."),
        ],
        "cta_title": "Precisa apenas de uma presença simples para começar?",
        "cta_text": "Envie os dados principais do negócio e veja uma primeira estrutura antes da publicação.",
        "cta_label": "Criar a minha página",
        "cta_route": "onboarding",
    },
    "process": {
        "meta_title": "Como funciona a criação do seu website | SiteExpress.pt",
        "meta_description": "Conheça o processo SiteExpress: informação do negócio, pré-visualização, revisão, publicação e evolução do website.",
        "eyebrow": "Como funciona",
        "title": "Do negócio ao website,",
        "title_emphasis": "sem labirintos.",
        "intro": "O processo foi preparado para pequenos negócios: recolher o essencial, mostrar uma pré-visualização, corrigir o que importa e publicar.",
        "primary_label": "Começar",
        "primary_route": "onboarding",
        "secondary_label": "Ver opções",
        "secondary_route": "pricing",
        "highlights": ["1. Enviar dados", "2. Pré-visualizar", "3. Rever", "4. Publicar"],
        "sections": [
            {
                "kicker": "Primeira fase",
                "title": "Conte-nos o suficiente para montar uma base real.",
                "body": "Pedimos o nome, atividade, localização, serviços, contactos, imagens e preferências principais. Se algo estiver em falta, tratamos disso durante a revisão.",
                "points": ["Escolha do produto", "Dados do negócio", "Serviços e área de atuação", "Cores, logótipo e imagens"],
            },
            {
                "kicker": "Revisão e publicação",
                "title": "A estrutura fica visível antes de se tornar o website final.",
                "body": "A pré-visualização permite corrigir informação, reorganizar prioridades e confirmar o caminho. A publicação e os serviços adicionais só avançam depois dessa revisão.",
                "points": ["Pré-visualização privada", "Correções combinadas", "Domínio e publicação", "Próximos passos de visibilidade"],
            },
        ],
        "cta_title": "O primeiro passo demora menos do que explicar tudo por telefone.",
        "cta_text": "Preencha a informação principal e deixe a estrutura mostrar o que ainda falta decidir.",
        "cta_label": "Iniciar projeto",
        "cta_route": "onboarding",
    },
    "printing": {
        "meta_title": "Impressão para pequenos negócios | SiteExpress.pt",
        "meta_description": "Cartões de visita, flyers, autocolantes QR e outros materiais para ligar a presença local ao website do seu negócio.",
        "eyebrow": "Impressão e presença local",
        "title": "Materiais físicos que levam clientes",
        "title_emphasis": "até ao seu website.",
        "intro": "Começamos por produtos simples e úteis. O objetivo é ajudar o negócio a divulgar contactos e criar uma ligação direta entre cartões, flyers, QR codes e a presença online.",
        "primary_label": "Ver cartões de visita",
        "primary_route": "business-cards",
        "secondary_label": "Pedir informação",
        "secondary_route": "contact",
        "highlights": ["Cartões de visita", "Flyers", "Autocolantes QR", "Pedidos personalizados"],
        "sections": [
            {
                "kicker": "Começar simples",
                "title": "Primeiro os produtos fáceis de produzir e repetir.",
                "body": "Cartões, flyers e autocolantes são os primeiros produtos previstos. Quantidades, acabamentos, ficheiros e prazos são confirmados antes de cada encomenda.",
                "points": ["Cartões de visita com QR", "Flyers de divulgação", "Autocolantes para montras e embalagens", "Menus, brochuras e outros pedidos sob consulta"],
            },
            {
                "kicker": "Ligação digital",
                "title": "O material impresso pode ser o início do website.",
                "body": "Os dados usados no cartão também ajudam a preparar uma presença online: nome, logótipo, cores, contactos e atividade. Mais tarde, o cliente poderá acompanhar o pedido e ver uma proposta de website no mesmo painel.",
                "points": ["QR para website ou contacto", "Dados reutilizados na pré-visualização", "Pedido acompanhado no futuro dashboard", "Website apresentado como próximo passo, sem pressão"],
            },
        ],
        "faqs": [
            ("Já posso encomendar todos os produtos?", "Começaremos apenas com os produtos para os quais produção, preço e entrega estejam confirmados. Os restantes podem ser pedidos para orçamento."),
            ("A SiteExpress faz a impressão?", "A SiteExpress gere o pedido e a ligação ao website. A produção poderá ser realizada por parceiros selecionados, sempre com as condições confirmadas antes da encomenda."),
            ("Posso incluir um QR code?", "Sim. O QR pode apontar para o website, contacto, localização ou outra página acordada."),
        ],
        "cta_title": "Precisa de cartões ou material simples para divulgar o negócio?",
        "cta_text": "Diga-nos o produto e a quantidade. Confirmamos opções, produção e entrega antes de avançar.",
        "cta_label": "Pedir informação",
        "cta_route": "contact",
    },
    "business-cards": {
        "meta_title": "Cartões de visita com QR code | SiteExpress.pt",
        "meta_description": "Cartões de visita para pequenos negócios com contactos, website, WhatsApp e QR code. Pedido acompanhado pela SiteExpress.",
        "eyebrow": "Cartões de visita",
        "title": "Um cartão simples que continua a trabalhar",
        "title_emphasis": "depois de ser entregue.",
        "intro": "Reunimos identidade, contactos e um QR code num cartão preparado para encaminhar clientes para o website, WhatsApp, localização ou página de contacto.",
        "primary_label": "Pedir cartões",
        "primary_route": "contact",
        "secondary_label": "Conhecer a impressão",
        "secondary_route": "printing",
        "highlights": ["Logótipo e cores", "Contacto e WhatsApp", "QR code", "Website ligado ao cartão"],
        "sections": [
            {
                "kicker": "Conteúdo essencial",
                "title": "Sem encher o cartão com tudo o que existe no negócio.",
                "body": "Organizamos apenas a informação que ajuda alguém a reconhecer, guardar e contactar a empresa. O QR leva o restante conteúdo para o ambiente digital.",
                "points": ["Nome e atividade", "Telefone, email ou WhatsApp", "Website ou página de destino", "QR code testado antes da produção"],
            },
            {
                "kicker": "Próximo passo",
                "title": "Os mesmos dados podem gerar uma primeira proposta de website.",
                "body": "O futuro dashboard de impressão mostrará a encomenda e, quando houver informação suficiente, uma pré-visualização simples da presença online do negócio.",
                "points": ["Acompanhamento da encomenda", "Reutilização do logótipo e cores", "Pré-visualização opcional do website", "Decisão separada da compra dos cartões"],
            },
        ],
        "faqs": [
            ("Quais quantidades estão disponíveis?", "As primeiras quantidades e acabamentos serão publicados depois da confirmação final com os fornecedores."),
            ("Posso enviar um design pronto?", "Sim. O ficheiro será verificado de acordo com as regras de produção antes de ser aceite."),
            ("O QR code tem custo adicional?", "A opção final e qualquer custo de preparação serão mostrados antes da encomenda."),
        ],
        "cta_title": "Envie o que já tem. Nós identificamos o que falta.",
        "cta_text": "Para começar, indique o negócio, quantidade aproximada e se já possui logótipo ou design.",
        "cta_label": "Contactar SiteExpress",
        "cta_route": "contact",
    },
    "contact": {
        "meta_title": "Contactos | SiteExpress.pt",
        "meta_description": "Contacte a SiteExpress para websites, Páginas Express, impressão e apoio digital para pequenos negócios em Portugal.",
        "eyebrow": "Contacto",
        "title": "Diga-nos o que o negócio precisa",
        "title_emphasis": "neste momento.",
        "intro": "Pode começar pelo formulário de projeto ou enviar um email. Indique o nome do negócio, localidade e se procura website, Página Express ou material impresso.",
        "primary_label": "Começar projeto",
        "primary_route": "onboarding",
        "secondary_label": "Enviar email",
        "secondary_url": "mailto:info@siteexpress.pt?subject=Pedido%20SiteExpress.pt",
        "highlights": ["info@siteexpress.pt", "Portugal", "Websites", "Impressão"],
        "sections": [
            {
                "kicker": "Para responder melhor",
                "title": "Quatro informações chegam para iniciar a conversa.",
                "body": "Não precisa preparar um documento. Uma mensagem curta permite perceber o ponto de partida e indicar o próximo passo.",
                "points": ["Nome e tipo de negócio", "Localidade ou área de serviço", "Produto ou objetivo", "Prazo, se existir"],
            },
            {
                "kicker": "Projetos de website",
                "title": "O formulário cria uma base mais útil do que uma troca longa de emails.",
                "body": "Se procura uma Página Express ou website WordPress, use o início de projeto para fornecer os dados essenciais e preparar a pré-visualização.",
                "points": ["Dados ficam ligados ao projeto", "Pode completar informação depois", "Ajuda a preparar a pré-visualização", "Sem publicação automática"],
            },
        ],
        "cta_title": "Pronto para começar com o essencial?",
        "cta_text": "Envie os dados do negócio ou escreva para info@siteexpress.pt.",
        "cta_label": "Começar projeto",
        "cta_route": "onboarding",
    },
}


PRICING_PAGE = {
    "meta_title": "Preços de websites e Páginas Express | SiteExpress.pt",
    "meta_description": "Compare Página Express, Website WordPress e manutenção para pequenos negócios em Portugal.",
    "eyebrow": "Preços",
    "title": "Opções claras para começar",
    "title_emphasis": "sem comprar tudo de uma vez.",
    "intro": "Escolha uma presença simples ou uma base WordPress completa. Impressão e funcionalidades adicionais são confirmadas separadamente.",
    "offers": [
        {
            "name": "Página Express",
            "price": "€19,95",
            "suffix": "/ mês",
            "description": "Para colocar o essencial online com uma página clara.",
            "features": ["Uma página", "Serviços principais", "Contacto e WhatsApp", "Possibilidade de upgrade"],
            "route": "starter-page",
            "label": "Ver Página Express",
        },
        {
            "name": "Website WordPress",
            "price": "€225",
            "suffix": "+ IVA",
            "description": "Para negócios que precisam de uma presença completa e expansível.",
            "features": ["Páginas essenciais", "Serviços detalhados", "Estrutura SEO básica", "Pré-visualização antes de publicar"],
            "route": "website-wordpress",
            "label": "Ver Website WordPress",
            "featured": True,
        },
        {
            "name": "Manutenção",
            "price": "€29,95",
            "suffix": "/ mês",
            "description": "Apoio contínuo para manter o website acompanhado.",
            "features": ["Manutenção básica", "Pequenas alterações combinadas", "Apoio com conteúdos", "Extras orçamentados antes"],
            "route": "contact",
            "label": "Pedir informação",
        },
    ],
    "note": "Domínio, alojamento, conteúdos adicionais, loja, línguas, impressão e integrações são confirmados conforme o projeto. Nenhum extra deve avançar sem preço apresentado.",
}


LEGAL_PAGES = {
    "privacy": {
        "meta_title": "Política de Privacidade | SiteExpress.pt",
        "title": "Política de Privacidade",
        "intro": "Esta página explica, de forma simples, como os dados enviados à SiteExpress são usados no contacto, preparação de projetos e prestação dos serviços pedidos.",
        "sections": [
            ("Dados recolhidos", "Podemos recolher nome, email, telefone, dados do negócio, conteúdos enviados, informação do projeto e dados técnicos necessários ao funcionamento e segurança do serviço."),
            ("Finalidades", "Os dados são usados para responder a pedidos, preparar pré-visualizações, gerir contas e projetos, prestar suporte, tratar encomendas e cumprir obrigações administrativas ou legais."),
            ("Assistente digital", "As mensagens enviadas no assistente e a página onde a conversa começou podem ser guardadas para responder, acompanhar utilização e melhorar o serviço. Quando o modo online estiver ativo, o conteúdo necessário à resposta pode ser processado pelo fornecedor de inteligência artificial. Não envie palavras-passe, dados de pagamento ou outros dados sensíveis no chat."),
            ("Partilha e fornecedores", "Os dados apenas devem ser partilhados com fornecedores necessários à prestação do serviço, como alojamento, email, pagamentos, análise técnica ou produção de materiais, dentro do âmbito necessário."),
            ("Conservação e direitos", "Os dados são mantidos pelo período necessário ao pedido, contrato e obrigações aplicáveis. Pode pedir acesso, correção ou eliminação através de info@siteexpress.pt, quando legalmente aplicável."),
            ("Contacto", "Questões relacionadas com privacidade podem ser enviadas para info@siteexpress.pt."),
        ],
    },
    "terms": {
        "meta_title": "Termos e Condições | SiteExpress.pt",
        "title": "Termos e Condições",
        "intro": "Estes termos apresentam as regras gerais dos pedidos feitos à SiteExpress. A proposta ou confirmação de cada serviço define o preço, âmbito e condições específicas aplicáveis.",
        "sections": [
            ("Propostas e encomendas", "Um serviço só é considerado aceite depois da confirmação do âmbito, preço e forma de pagamento. Pedidos iniciais e pré-visualizações não representam publicação ou produção automática."),
            ("Conteúdos do cliente", "O cliente deve fornecer informação correta e possuir autorização para usar textos, imagens, logótipos, marcas e outros materiais entregues para o projeto."),
            ("Revisões e trabalho adicional", "As revisões incluídas devem ser indicadas na proposta. Alterações fora do âmbito, novas páginas, integrações ou reconstruções podem exigir novo orçamento."),
            ("Serviços recorrentes", "Mensalidades, renovação, cancelamento e efeitos sobre alojamento, domínio ou funcionalidades são apresentados antes da ativação do plano."),
            ("Impressão personalizada", "Produção, ficheiros, quantidades, prazos e entrega são confirmados antes de uma encomenda de impressão. Produtos personalizados podem ter condições específicas de cancelamento e devolução."),
            ("Contacto", "Dúvidas sobre um pedido ou estes termos podem ser enviadas para info@siteexpress.pt."),
        ],
    },
    "cookies": {
        "meta_title": "Política de Cookies | SiteExpress.pt",
        "title": "Política de Cookies",
        "intro": "A SiteExpress pode usar cookies necessários ao funcionamento do website e, quando ativados, cookies de análise para compreender utilização e melhorar as páginas.",
        "sections": [
            ("Cookies necessários", "Ajudam a manter sessões, segurança, preferências técnicas e funções essenciais. Sem estes cookies, algumas áreas podem não funcionar corretamente."),
            ("Armazenamento local", "O assistente pode guardar no navegador um identificador técnico de conversa para manter o contexto entre páginas. Este identificador não contém a mensagem nem dados de pagamento."),
            ("Análise", "Ferramentas de análise podem registar interações técnicas e agregadas para identificar problemas e melhorar a experiência. A utilização deve respeitar as opções de consentimento aplicáveis."),
            ("Gestão no navegador", "Pode bloquear ou eliminar cookies através das definições do navegador. O bloqueio de cookies essenciais pode afetar autenticação, formulários ou outras funcionalidades."),
            ("Contacto", "Questões sobre cookies podem ser enviadas para info@siteexpress.pt."),
        ],
    },
}
